/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh access token */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brand-catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List brand catalog */
        get: operations["listBrandCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brand-catalog/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search brand catalog */
        get: operations["searchBrandCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List user projects */
        get: operations["listProjects"];
        put?: never;
        /** Create a project */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["projectID"];
            };
            cookie?: never;
        };
        /** Get project by ID */
        get: operations["getProject"];
        /** Update project */
        put: operations["updateProject"];
        post?: never;
        /** Delete project */
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectID}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["projectID"];
            };
            cookie?: never;
        };
        /** List project sources */
        get: operations["listSources"];
        put?: never;
        /** Create a source */
        post: operations["createSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectID}/sources/{sourceID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["projectID"];
                sourceID: components["parameters"]["sourceID"];
            };
            cookie?: never;
        };
        get?: never;
        /** Update a source */
        put: operations["updateSource"];
        post?: never;
        /** Delete a source */
        delete: operations["deleteSource"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectID}/sources/{sourceID}/toggle": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["projectID"];
                sourceID: components["parameters"]["sourceID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Toggle source status */
        post: operations["toggleSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectID}/brand": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["projectID"];
            };
            cookie?: never;
        };
        /** Get brand settings for project */
        get: operations["getBrand"];
        /** Update brand settings */
        put: operations["updateBrand"];
        /** Create brand for project */
        post: operations["createBrand"];
        /** Delete brand */
        delete: operations["deleteBrand"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectID}/feed": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["projectID"];
            };
            cookie?: never;
        };
        /** List mentions feed */
        get: operations["listFeed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectID}/feed/{mentionID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["projectID"];
                mentionID: components["parameters"]["mentionID"];
            };
            cookie?: never;
        };
        /** Get mention details */
        get: operations["getMention"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectID}/feed/{mentionID}/duplicates": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["projectID"];
                mentionID: components["parameters"]["mentionID"];
            };
            cookie?: never;
        };
        /** List mention duplicates */
        get: operations["listDuplicates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectID}/feed/{mentionID}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["projectID"];
                mentionID: components["parameters"]["mentionID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dismiss a mention */
        post: operations["dismissMention"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectID}/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["projectID"];
            };
            cookie?: never;
        };
        /** Analytics summary */
        get: operations["analyticsSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectID}/analytics/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["projectID"];
            };
            cookie?: never;
        };
        /** Mentions timeline */
        get: operations["analyticsTimeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectID}/analytics/sentiment": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["projectID"];
            };
            cookie?: never;
        };
        /** Sentiment distribution */
        get: operations["analyticsSentiment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectID}/analytics/sources": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["projectID"];
            };
            cookie?: never;
        };
        /** Top sources by mention count */
        get: operations["analyticsSources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectID}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["projectID"];
            };
            cookie?: never;
        };
        /** List project events */
        get: operations["listEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectID}/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["projectID"];
            };
            cookie?: never;
        };
        /** List project alerts */
        get: operations["listAlerts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectID}/alert-config": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["projectID"];
            };
            cookie?: never;
        };
        /** Get alert configuration */
        get: operations["getAlertConfig"];
        /** Create or update alert configuration */
        put: operations["upsertAlertConfig"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: string;
            details?: string;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        RefreshRequest: {
            refresh_token: string;
        };
        AuthTokens: {
            access_token?: string;
            refresh_token?: string;
            user?: components["schemas"]["User"];
        };
        User: {
            /** Format: uuid */
            id?: string;
            /** Format: email */
            email?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        CreateProjectRequest: {
            name: string;
            description?: string | null;
        };
        UpdateProjectRequest: {
            name: string;
            description?: string | null;
        };
        Project: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            user_id?: string;
            name?: string;
            description?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        CreateSourceRequest: {
            /** @enum {string} */
            type: "rss" | "web" | "telegram";
            name: string;
            /** Format: uri */
            url: string;
            config?: Record<string, never>;
        };
        UpdateSourceRequest: {
            name: string;
            /** Format: uri */
            url: string;
            config?: Record<string, never>;
        };
        Source: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            project_id?: string;
            /** @enum {string} */
            type?: "rss" | "web" | "telegram" | "site";
            name?: string;
            url?: string;
            config?: Record<string, never>;
            /** @enum {string} */
            status?: "active" | "error" | "disabled";
            /** Format: date-time */
            last_fetched_at?: string | null;
            last_error?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        CreateBrandRequest: {
            catalog_id?: number | null;
            name: string;
            keywords: string[];
            exclusions?: string[];
            risk_words?: string[];
        };
        UpdateBrandRequest: {
            catalog_id?: number | null;
            name: string;
            keywords: string[];
            exclusions?: string[];
            risk_words?: string[];
        };
        Brand: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            project_id?: string;
            catalog_id?: number | null;
            name?: string;
            keywords?: string[];
            exclusions?: string[];
            risk_words?: string[];
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        BrandCatalog: {
            id?: number;
            slug?: string;
            name?: string;
            source_url?: string;
            /** Format: date-time */
            created_at?: string;
        };
        BrandCatalogList: {
            data?: components["schemas"]["BrandCatalog"][];
            total?: number;
        };
        MentionRow: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            project_id?: string;
            /** Format: uuid */
            source_id?: string;
            /** Format: uuid */
            brand_id?: string;
            external_id?: string;
            title?: string | null;
            text?: string;
            url?: string | null;
            author?: string | null;
            /** Format: date-time */
            published_at?: string;
            matched_keywords?: string[];
            matched_risk_words?: string[];
            sentiment_label?: string | null;
            /** Format: double */
            sentiment_score?: number | null;
            is_duplicate?: boolean;
            /** @enum {string} */
            status?: "pending_ml" | "enriched" | "ready" | "dismissed";
            /** Format: date-time */
            created_at?: string;
        };
        AnalyticsSummary: {
            /** Format: int64 */
            total_mentions?: number;
            sentiment_counts?: {
                [key: string]: number;
            };
            top_sources?: components["schemas"]["SourceMentionCount"][];
        };
        SourceMentionCount: {
            /** Format: uuid */
            source_id?: string;
            /** Format: int64 */
            count?: number;
        };
        TimelinePoint: {
            /** Format: date-time */
            bucket?: string;
            /** Format: int64 */
            count?: number;
            sentiment?: string;
        };
        EventRow: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            project_id?: string | null;
            /** Format: uuid */
            source_id?: string | null;
            type?: string;
            message?: string;
            /** Format: date-time */
            created_at?: string;
        };
        AlertRow: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            project_id?: string;
            type?: string;
            mention_count?: number;
            threshold?: number;
            sentiment_summary?: Record<string, never>;
            /** @enum {string} */
            status?: "pending" | "sent" | "failed";
            /** Format: date-time */
            sent_at?: string | null;
            /** Format: date-time */
            created_at?: string;
        };
        AlertConfig: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            project_id?: string;
            spike_threshold?: number;
            spike_window_minutes?: number;
            cooldown_minutes?: number;
            notification_channels?: Record<string, never>[];
            enabled?: boolean;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        UpsertAlertConfigRequest: {
            spike_threshold: number;
            spike_window_minutes: number;
            cooldown_minutes: number;
            notification_channels?: Record<string, never>[];
            enabled: boolean;
        };
        HealthResponse: {
            /** @enum {string} */
            status?: "ok" | "degraded";
            database?: string;
            redis?: string;
            nats?: string;
        };
    };
    responses: {
        /** @description Unauthorized */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Not Found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Conflict */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Validation Error */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        projectID: string;
        sourceID: string;
        mentionID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokens"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokens"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokens"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listBrandCatalog: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandCatalogList"];
                };
            };
        };
    };
    searchBrandCatalog: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandCatalog"][];
                };
            };
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["projectID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["projectID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["projectID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    listSources: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["projectID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Source"][];
                };
            };
        };
    };
    createSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["projectID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSourceRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Source"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    updateSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["projectID"];
                sourceID: components["parameters"]["sourceID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSourceRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Source"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    deleteSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["projectID"];
                sourceID: components["parameters"]["sourceID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    toggleSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["projectID"];
                sourceID: components["parameters"]["sourceID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Source"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getBrand: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["projectID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Brand"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateBrand: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["projectID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBrandRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Brand"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    createBrand: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["projectID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBrandRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Brand"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    deleteBrand: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["projectID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    listFeed: {
        parameters: {
            query?: {
                sentiment?: "positive" | "negative" | "neutral" | "unknown";
                status?: "pending_ml" | "enriched" | "ready" | "dismissed";
                /** @description RFC 3339 datetime */
                since?: string;
                /** @description RFC 3339 datetime */
                until?: string;
                brand_id?: string;
                source_id?: string;
                search?: string;
                has_risk?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                projectID: components["parameters"]["projectID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MentionRow"][];
                };
            };
        };
    };
    getMention: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["projectID"];
                mentionID: components["parameters"]["mentionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MentionRow"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listDuplicates: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["projectID"];
                mentionID: components["parameters"]["mentionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MentionRow"][];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    dismissMention: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["projectID"];
                mentionID: components["parameters"]["mentionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example dismissed */
                        status?: string;
                    };
                };
            };
        };
    };
    analyticsSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["projectID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsSummary"];
                };
            };
        };
    };
    analyticsTimeline: {
        parameters: {
            query?: {
                /** @description RFC 3339 datetime */
                since?: string;
                /** @description RFC 3339 datetime */
                until?: string;
                interval?: "hour" | "day";
            };
            header?: never;
            path: {
                projectID: components["parameters"]["projectID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelinePoint"][];
                };
            };
        };
    };
    analyticsSentiment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["projectID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
        };
    };
    analyticsSources: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["projectID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceMentionCount"][];
                };
            };
        };
    };
    listEvents: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                projectID: components["parameters"]["projectID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventRow"][];
                };
            };
        };
    };
    listAlerts: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                projectID: components["parameters"]["projectID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRow"][];
                };
            };
        };
    };
    getAlertConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["projectID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertConfig"];
                };
            };
        };
    };
    upsertAlertConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectID: components["parameters"]["projectID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertAlertConfigRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertConfig"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
}
